[package]
name = "matan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["bundled"]

[[test]]
name = "grtests"
path = "grtests/main.rs"
harness = false